export enum AssignmentStatus {
  NOTSEND = 'NOTSEND',
  SEND = 'SEND',
  TURNINLATE = 'TURNINLATE',
  REJECT_ADVISOR = 'REJECT_ADVISOR',
  APPROVE_ADVISOR = 'APPROVE_ADVISOR',
  REJECT_PROCTOR = 'REJECT_PROCTOR',
  APPROVE_PROCTOR = 'APPROVE_PROCTOR',
}
